<div>
    <div class="mb-8"><a href="{{ route('backoffice.projects.index') }}" class="text-sm text-slate-400 hover:text-white">← Retour aux projets</a><p class="mt-6 font-mono text-xs uppercase tracking-[0.2em] text-blue-400">{{ $editing ? 'Édition' : 'Création' }}</p><h1 class="mt-2 text-3xl font-semibold text-white">{{ $editing ? 'Modifier le projet' : 'Nouveau projet' }}</h1></div>
    @if ($errors->any())<div class="mb-5 rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300"><ul class="list-disc space-y-1 pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form wire:submit="save" class="space-y-6">
        <section class="rounded-xl border border-slate-800 bg-slate-900 p-5 sm:p-7"><h2 class="mb-5 text-lg font-semibold text-white">Informations principales</h2><div class="grid gap-5 sm:grid-cols-2"><x-admin.input label="Nom" model="name" required /><x-admin.input label="Slug" model="slug" required /><x-admin.input label="Version" model="version" /><x-admin.input label="Prix" model="price" type="number" step="0.01" /><x-admin.input label="URL du projet" model="url" type="url" /><x-admin.input label="Dépôt Git" model="repositoryUrl" type="url" /></div><div class="mt-5"><x-admin.textarea label="Description" model="description" rows="5" /></div></section>
        <section class="rounded-xl border border-slate-800 bg-slate-900 p-5 sm:p-7"><h2 class="mb-5 text-lg font-semibold text-white">Médias Cloudinary</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm text-slate-300">Couverture</label><input wire:model="cover" type="file" accept="image/*" class="block w-full text-sm text-slate-400 file:mr-4 file:rounded-lg file:border-0 file:bg-blue-600 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-blue-500">@if ($cover)<p class="mt-2 text-xs text-blue-300">Fichier prêt à être envoyé vers Cloudinary.</p>@elseif ($editing && $project?->image)<img src="{{ $project->image }}" alt="" class="mt-3 h-32 w-full rounded-lg object-cover">@endif</div><div><label class="mb-2 block text-sm text-slate-300">Aperçus supplémentaires</label><input wire:model="gallery" type="file" accept="image/*" multiple class="block w-full text-sm text-slate-400 file:mr-4 file:rounded-lg file:border-0 file:bg-blue-600 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-blue-500"><p class="mt-2 text-xs text-slate-500">Les fichiers sont envoyés directement à Cloudinary lors de l’enregistrement.</p></div></div></section>
        <section class="rounded-xl border border-slate-800 bg-slate-900 p-5 sm:p-7"><h2 class="mb-5 text-lg font-semibold text-white">Classification</h2><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><x-admin.select label="Statut" model="status" :options="$statusOptions" /><x-admin.select label="Type" model="type" :options="$typeOptions" /><x-admin.select label="Complexité" model="complexity" :options="$complexityOptions" /><x-admin.select label="Visibilité" model="visibility" :options="$visibilityOptions" /></div><div class="mt-5 grid gap-5 sm:grid-cols-2"><x-admin.select label="Stack" model="stackId" :options="$stacks->pluck('name', 'id')->all()" placeholder="Aucune" /><x-admin.select label="Infrastructure" model="infraId" :options="$infras->pluck('name', 'id')->all()" placeholder="Aucune" /></div></section>
        <section class="rounded-xl border border-slate-800 bg-slate-900 p-5 sm:p-7"><h2 class="mb-5 text-lg font-semibold text-white">Relations</h2><div class="grid gap-5 sm:grid-cols-2"><x-admin.multi-select label="Compétences" model="skillIds" :options="$skills->pluck('name', 'id')->all()" /><x-admin.multi-select label="Catégories" model="categoryIds" :options="$categories->pluck('name', 'id')->all()" /></div></section>
        <div class="flex justify-end gap-3"><a href="{{ route('backoffice.projects.index') }}" class="rounded-lg border border-slate-700 px-4 py-2 text-sm font-semibold text-slate-300 hover:bg-slate-800">Annuler</a><button wire:loading.attr="disabled" type="submit" class="rounded-lg bg-blue-600 px-5 py-2 text-sm font-semibold text-white hover:bg-blue-500 disabled:opacity-50"><span wire:loading.remove>Enregistrer</span><span wire:loading>Envoi vers Cloudinary...</span></button></div>
    </form>
</div>
