<div class="space-y-8">
    <div class="flex flex-wrap items-end justify-between gap-4">
        <div><p class="font-mono text-xs uppercase tracking-[0.2em] text-blue-400">Control room · {{ now()->format('d M Y') }}</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Tableau de bord</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Vue opérationnelle du portfolio, de son contenu, de son trafic et de son infrastructure.</p></div>
        <div class="flex gap-3"><button wire:click="$refresh" class="rounded-lg border border-slate-700 px-4 py-2 text-sm font-medium text-slate-300 transition hover:bg-slate-800">Rafraîchir</button><a href="{{ route('backoffice.projects.create') }}" class="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-blue-500">Nouveau projet</a></div>
    </div>

    <section><div class="mb-3 flex items-center justify-between"><div><p class="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-600">01 · Vue d'ensemble</p><h2 class="mt-1 text-lg font-semibold text-white">Indicateurs clés</h2></div></div><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@foreach($overview as $stat)<div class="rounded-xl border border-slate-800 bg-slate-900 p-5 transition hover:border-blue-500/40"><div class="flex items-start justify-between"><p class="text-sm text-slate-400">{{ $stat['label'] }}</p><span class="h-2 w-2 rounded-full bg-{{ $stat['tone'] }}-400"></span></div><p class="mt-4 text-3xl font-semibold tracking-tight text-white">{{ number_format($stat['value']) }}</p><p class="mt-1 text-xs text-slate-500">{{ $stat['detail'] }}</p></div>@endforeach</div></section>

    <section class="rounded-xl border border-slate-800 bg-slate-900 p-5 sm:p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-600">02 · Observabilité</p><h2 class="mt-1 text-lg font-semibold text-white">Trafic public</h2><p class="mt-1 text-sm text-slate-500">Fréquentation hors bots.</p></div><div class="grid grid-cols-2 gap-4 text-right sm:grid-cols-4">@foreach($trafficStats as $stat)<div><p class="font-mono text-xl font-semibold text-blue-300">{{ number_format($stat['value']) }}</p><p class="mt-1 text-[11px] text-slate-500">{{ $stat['label'] }}</p></div>@endforeach</div></div><div class="mt-8 flex h-40 items-end gap-1 border-b border-l border-slate-800 px-2 pb-0">@php($maxTraffic = max(1, collect($trafficSeries)->max('value'))) @foreach($trafficSeries as $point)<div class="group relative flex h-full flex-1 items-end"><div class="w-full rounded-t bg-blue-500/60 transition group-hover:bg-blue-400" style="height: {{ max(3, ($point['value'] / $maxTraffic) * 100) }}%"></div><span class="pointer-events-none absolute bottom-full left-1/2 mb-2 hidden -translate-x-1/2 rounded bg-slate-800 px-2 py-1 font-mono text-[10px] text-white group-hover:block">{{ $point['value'] }}</span></div>@endforeach</div><div class="mt-3 flex justify-between font-mono text-[10px] text-slate-600"><span>{{ $trafficSeries[0]['label'] }}</span><span>{{ $trafficSeries[count($trafficSeries) - 1]['label'] }}</span></div></section>

    <section class="grid gap-5 xl:grid-cols-3"><x-admin.dashboard-card title="Visites par langue" eyebrow="30 derniers jours"><div class="space-y-4">@php($localeTotal = max(1, array_sum(array_column($localeSeries, 'value')))) @foreach($localeSeries as $item)<div><div class="mb-1 flex justify-between text-sm"><span class="text-slate-300">{{ $item['label'] }}</span><span class="font-mono text-slate-500">{{ $item['value'] }}</span></div><div class="h-2 rounded-full bg-slate-800"><div class="h-2 rounded-full bg-blue-500" style="width: {{ ($item['value'] / $localeTotal) * 100 }}%"></div></div></div>@endforeach</div></x-admin.dashboard-card><x-admin.dashboard-card title="Projets par statut" eyebrow="Cycle de vie"><div class="space-y-3">@php($statusTotal = max(1, array_sum(array_column($projectStatuses, 'value')))) @foreach($projectStatuses as $item)<div class="flex items-center justify-between border-b border-slate-800 pb-2 text-sm"><span class="text-slate-300">{{ $item['label'] }}</span><span class="font-mono text-blue-300">{{ $item['value'] }}</span></div>@endforeach</div></x-admin.dashboard-card><x-admin.dashboard-card title="Pages les plus visitées" eyebrow="Top 10 · 30 jours"><div class="space-y-3">@forelse($topPages as $path => $count)<div class="flex items-center justify-between gap-4 text-sm"><span class="truncate font-mono text-slate-400">{{ $path }}</span><span class="font-mono text-slate-500">{{ $count }}</span></div>@empty<p class="text-sm text-slate-500">Aucune visite enregistrée.</p>@endforelse</div></x-admin.dashboard-card></section>

    <section class="grid gap-5 xl:grid-cols-3"><x-admin.dashboard-card title="Publications" eyebrow="12 derniers mois"><div class="flex h-28 items-end gap-1">@php($publicationMax = max(1, collect($publicationSeries)->max('value'))) @foreach($publicationSeries as $point)<div class="group relative flex h-full flex-1 items-end"><div class="w-full rounded-t bg-blue-500/60" style="height: {{ max(4, ($point['value'] / $publicationMax) * 100) }}%" title="{{ $point['label'] }}: {{ $point['value'] }}"></div></div>@endforeach</div><p class="mt-3 text-xs text-slate-500">Articles publiés par mois</p></x-admin.dashboard-card><x-admin.dashboard-card title="Messages" eyebrow="6 derniers mois"><div class="flex h-28 items-end gap-1">@php($messageMax = max(1, collect($messageSeries)->max('value'))) @foreach($messageSeries as $point)<div class="group relative flex h-full flex-1 items-end"><div class="w-full rounded-t bg-amber-400/70" style="height: {{ max(4, ($point['value'] / $messageMax) * 100) }}%" title="{{ $point['label'] }}: {{ $point['value'] }}"></div></div>@endforeach</div><p class="mt-3 text-xs text-slate-500">Demandes reçues par mois</p></x-admin.dashboard-card><x-admin.dashboard-card title="Activité admin" eyebrow="14 derniers jours"><div class="flex h-28 items-end gap-1">@php($activityMax = max(1, collect($activitySeries)->max('value'))) @foreach($activitySeries as $point)<div class="group relative flex h-full flex-1 items-end"><div class="w-full rounded-t bg-emerald-400/70" style="height: {{ max(4, ($point['value'] / $activityMax) * 100) }}%" title="{{ $point['label'] }}: {{ $point['value'] }}"></div></div>@endforeach</div><p class="mt-3 text-xs text-slate-500">Actions enregistrées</p></x-admin.dashboard-card></section>

    <section><div class="mb-3"><p class="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-600">03 · Contenu</p><h2 class="mt-1 text-lg font-semibold text-white">Santé éditoriale</h2></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">@foreach($contentStats as $group)<div class="rounded-xl border border-slate-800 bg-slate-900 p-5"><h3 class="font-semibold text-white">{{ $group['title'] }}</h3><div class="mt-4 grid grid-cols-2 gap-3">@foreach($group['items'] as $item)<div class="rounded-lg bg-slate-950/70 p-3"><p class="font-mono text-xl text-blue-300">{{ number_format($item['value']) }}</p><p class="mt-1 text-xs text-slate-500">{{ $item['label'] }}</p></div>@endforeach</div></div>@endforeach</div></section>

    <section class="grid gap-5 xl:grid-cols-2"><x-admin.dashboard-card title="Projets par stack" eyebrow="Répartition technique"><div class="space-y-3">@forelse($stackDistribution as $item)<div><div class="mb-1 flex justify-between text-sm"><span class="text-slate-300">{{ $item->name }}</span><span class="font-mono text-slate-500">{{ $item->projects_count }}</span></div><div class="h-1.5 rounded-full bg-slate-800"><div class="h-1.5 rounded-full bg-blue-500" style="width: {{ min(100, $item->projects_count * 20) }}%"></div></div></div>@empty<p class="text-sm text-slate-500">Aucune stack configurée.</p>@endforelse</div></x-admin.dashboard-card><x-admin.dashboard-card title="Infrastructure" eyebrow="Capacité provisionnée"><div class="grid grid-cols-2 gap-3 sm:grid-cols-3">@foreach($infraStats as $stat)<div class="rounded-lg bg-slate-950/70 p-3"><p class="font-mono text-lg text-emerald-300">{{ $stat['value'] }}</p><p class="mt-1 text-xs text-slate-500">{{ $stat['label'] }}</p></div>@endforeach</div></x-admin.dashboard-card></section>

    <section class="grid gap-5 xl:grid-cols-3"><x-admin.dashboard-card title="Compétences par niveau" eyebrow="Maîtrise"><div class="space-y-3">@foreach($skillLevels as $item)<div class="flex items-center justify-between border-b border-slate-800 pb-2 text-sm"><span class="text-slate-300">{{ $item['label'] }}</span><span class="font-mono text-blue-300">{{ $item['value'] }}</span></div>@endforeach</div></x-admin.dashboard-card><x-admin.dashboard-card title="Compétences par catégorie" eyebrow="Répartition"><div class="space-y-3">@forelse($skillsByCategory as $item)<div class="flex items-center justify-between text-sm"><span class="truncate text-slate-300">{{ $item->name }}</span><span class="font-mono text-slate-500">{{ $item->skills_count }}</span></div>@empty<p class="text-sm text-slate-500">Aucune catégorie.</p>@endforelse</div></x-admin.dashboard-card><x-admin.dashboard-card title="Journal d'activité" eyebrow="Traçabilité"><div class="grid grid-cols-2 gap-3">@foreach($auditStats as $stat)<div class="rounded-lg bg-slate-950/70 p-3"><p class="font-mono text-lg text-blue-300">{{ number_format($stat['value']) }}</p><p class="mt-1 text-xs text-slate-500">{{ $stat['label'] }}</p></div>@endforeach</div></x-admin.dashboard-card></section>

    <section class="grid gap-5 xl:grid-cols-2"><x-admin.dashboard-card title="Messages récents" eyebrow="Boîte de réception"><div class="divide-y divide-slate-800">@forelse($messages as $message)<div class="flex items-center gap-3 py-3"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full {{ $message->isRead() ? 'bg-slate-800 text-slate-500' : 'bg-blue-500/15 text-blue-300' }} text-xs font-semibold">{{ strtoupper(mb_substr($message->name, 0, 1)) }}</span><div class="min-w-0 flex-1"><p class="truncate text-sm font-medium text-slate-200">{{ $message->name }} · {{ $message->subject }}</p><p class="text-xs text-slate-500">{{ $message->created_at?->diffForHumans() }}</p></div>@if(! $message->isRead())<a href="{{ route('backoffice.resource.index', 'messages') }}" class="text-xs text-blue-400">Ouvrir</a>@endif</div>@empty<p class="py-5 text-sm text-slate-500">Aucun message.</p>@endforelse</div></x-admin.dashboard-card><x-admin.dashboard-card title="Activité récente" eyebrow="Journal admin"><div class="divide-y divide-slate-800">@forelse($activities as $activity)<div class="flex gap-3 py-3"><span class="mt-1 h-2 w-2 shrink-0 rounded-full bg-blue-400"></span><div><p class="text-sm text-slate-300">{{ $activity->description ?: $activity->action }}</p><p class="text-xs text-slate-600">{{ $activity->user?->name ?? '-' }} · {{ $activity->created_at?->diffForHumans() }}</p></div></div>@empty<p class="py-5 text-sm text-slate-500">Aucune activité.</p>@endforelse</div></x-admin.dashboard-card></section>

    <section class="grid gap-5 xl:grid-cols-2"><x-admin.dashboard-card title="Projets récents" eyebrow="Portefeuille"><div class="divide-y divide-slate-800">@forelse($recentProjects as $project)<a href="{{ route('backoffice.projects.edit', $project) }}" class="flex items-center justify-between gap-4 py-3 transition hover:text-blue-300"><span class="truncate text-sm text-slate-300">{{ $project->name }}</span><span class="font-mono text-xs text-slate-500">{{ $project->status?->label() }}</span></a>@empty<p class="py-5 text-sm text-slate-500">Aucun projet.</p>@endforelse</div></x-admin.dashboard-card><x-admin.dashboard-card title="Projets sans média" eyebrow="À compléter"><div class="divide-y divide-slate-800">@forelse($missingMedia as $project)<a href="{{ route('backoffice.projects.edit', $project) }}" class="flex items-center justify-between gap-4 py-3 text-sm"><span class="truncate text-slate-300">{{ $project->name }}</span><span class="text-xs text-blue-400">Ajouter →</span></a>@empty<p class="py-5 text-sm text-emerald-300">Tous les projets sont illustrés.</p>@endforelse</div></x-admin.dashboard-card></section>

    <section class="rounded-xl border border-slate-800 bg-slate-900 p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="font-mono text-[10px] uppercase tracking-[0.2em] text-slate-600">04 · Actions</p><h2 class="mt-1 text-lg font-semibold text-white">Raccourcis opérationnels</h2></div><div class="flex flex-wrap gap-2"><a href="{{ route('backoffice.projects.create') }}" class="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white hover:bg-blue-500">Nouveau projet</a><a href="{{ route('backoffice.resource.index', 'messages') }}" class="rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800">Voir les messages</a><a href="{{ route('backoffice.resource.index', 'skills') }}" class="rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800">Compétences</a><a href="{{ route('backoffice.resource.index', 'stacks') }}" class="rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300 hover:bg-slate-800">Stacks</a></div></div></section>
</div>
